#!/bin/sh
BINFILE=$2
SDCARD=$1
BINFILE=u-boot-aml.bin
 
#aml-debug-rom-sd.bin
#u-boot-aml.bin 
sudo dd if=${BINFILE} of=$1 bs=1 count=444 
sudo dd if=${BINFILE} of=$1 bs=512 skip=1 seek=1 
eject $1
echo FINISH
