#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 *
 */

#define TASK_STATE 0 /* offsetof(struct task_struct, state)	; */
#define TASK_FLAGS 12 /* offsetof(struct task_struct, flags)	; */
#define TASK_PTRACE 16 /* offsetof(struct task_struct, ptrace)	; */
#define TASK_THREAD 424 /* offsetof(struct task_struct, thread)	; */
#define TASK_MM 128 /* offsetof(struct task_struct, mm)	; */
#define TASK_PID 164 /* offsetof(struct task_struct, pid)	; */
#define TASK_THREAD_INFO 4 /* offsetof(struct task_struct, thread_info)	; */

#define THREAD_KSP 0 /* offsetof(struct thread_struct, ksp)	; */
#define THREAD_USP 4 /* offsetof(struct thread_struct, usp)	; */
#define THREAD_PC 8 /* offsetof(struct thread_struct, pc)	; */

#define THREAD_INFO_FLAGS 8 /* offsetof(struct thread_info, flags)	; */
#define THREAD_INFO_PREEMPT_COUNT 20 /* offsetof(struct thread_info, preempt_count)	; */
#define CPUSTAT_SOFTIRQ_PENDING 0 /* offsetof(irq_cpustat_t, __softirq_pending)	; */
#define CPUSTAT_LOCAL_IRQ_COUNT 4 /* offsetof(irq_cpustat_t, __local_irq_count)	; */

#define TASK_ACT_MM 132 /* offsetof(struct task_struct, active_mm)	; */
#define TASK_TGID 168 /* offsetof(struct task_struct, tgid)	; */
#define MM_CTXT 348 /* offsetof(struct mm_struct, context)	; */
#define MM_PGD 36 /* offsetof(struct mm_struct, pgd)	; */
#define MM_CTXT_ASID 0 /* offsetof(mm_context_t, asid)	; */

#endif
